---
title: "CalSIMETAW comparison"
author: "Anna Boser"
date: "2022-12-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(here)
library(dplyr)
library(ggplot2)
library(tidyr)
library(stringr)
library(ggrepel)
library(lfe)

source(here("file_paths.R"))
```

```{r}
experiment_name <- "fallow_3-9_gb"
experiment_path <- here("data", "4_for_analysis", "ML_outputs",  "experiments", experiment_name)
```


# Diagnostics
```{r}
# disgnostics: is simulated natural ET higher any given month? 
c <- fread(here(experiment_path, "time_series_by_crop.csv"))
sc <- fread(here(experiment_path, "time_series_by_subcrop.csv"))

ggplot(c) + 
  geom_line(aes(x = month, y = ET, color = "Observed ET")) + 
  geom_line(aes(x = month, y = ET_pred, color = "Simulated natural ET")) + 
  facet_wrap(vars(cropnames))

ggplot(sc) + 
  geom_line(aes(x = month, y = ET, color = "Observed ET")) + 
  geom_line(aes(x = month, y = ET_pred, color = "Simulated natural ET")) + 
  facet_wrap(vars(subcropnames))
```

## Compare my estimates of crop water use and irrigation water use to CalSIMETAW outputs
Data from: https://data.ca.gov/dataset/cal-simetaw-unit-values

```{r}
CS <- fread(calsimetaw_loc)

# keep only counties of interest
counties <- c("Tehama", "Glenn", "Butte", "Colusa", "Sutter", "Yuba", "Yolo", "Solano", "Sacramento", "San Joaquin", "Stanislaus", "Merced", "Madera", "Fresno", "Kings", "Tulare", "Kern")

CS <- filter(CS, COUNTY_NAME %in% counties)

# get mm/day 
CS$Date <- as.Date(CS$Date)
CS$year <- year(CS$Date + 92) # add three months to get the water year
CS$month <- month(CS$Date)

# subcrop lookup table. The rule is first look in the general crop types, if it's not there look in the subcrop types. 
l = c("Grain" = "Grain and hay crops", 
      "Rice" = "Rice", 
      "Cotton" = "Cotton", 
      "Sugar Beets" = NA, # "Truck, nursery, and berry crops", 
      "Corn" = "Corn,Sorghum or Sudan", # "Field crops",
      "Dry Beans" = "Beans (dry)", # "Truck, nursery, and berry crops",
      "Safflower" = "Safflower", # "Field crops",
      "Other Field" = "Field crops",
      "Alfalfa" = "Alfalfa & alfalfa mixtures", # "Grain and hay crops", 
      "Pasture" = "Pasture", 
      "Tomato Processing" = "Tomatoes (processing)", 
      "Tomato Fresh" = NA, # "Truck, nursery, and berry crops", 
      "Cucurbits" = "Melons", # "Truck, nursery, and berry crops", 
      "Onions & Garlic" = "Onions & garlic", # "Truck, nursery, and berry crops", 
      "Potatoes" = "Potato or Sweet potato", # "Truck, nursery, and berry crops", 
      "Truck Crops" = "Truck, nursery, and berry crops", 
      "Almond & Pistacios" = "Almond & Pistacios", # "Deciduous fruits and nuts", 
      "Other Decidious" = "Deciduous fruits and nuts", 
      "Citrus & Subtropical" = "Citrus and subtropical", 
      "Vineyard" = "Vineyards", 
      "Urban Landscape" = NA, 
      "Riparian" = NA, 
      "Native Vegetation" = NA, 
      "Water Surface" = NA)

CS$cropnames = l[CS$CROP_NAME]
CS <- filter(CS, !is.na(cropnames))
```

# lazy version without standard errors: 
```{r}
# get the monthly ET by crop dataset
df <- fread(here(experiment_path, "agriculture_monthly_county_crop.csv"))
df <- filter(df, cropnames %in% CS$cropnames)
CS <- merge(CS, df, by = c("cropnames", "COUNTY_NAME", "month"))

# average by CalSIMETAW county and crop type. get mm/da instead of mm/month
scatter_data <- CS %>% 
  group_by(COUNTY_NAME, cropnames) %>% 
  summarize(ETo = mean(ETo), 
            ag_ET_need = mean(ifelse(ETc>Pcp, ETc-Pcp, 0)), 
            ETc_ET_pred = mean(ifelse(ETc>ET_pred, ETc-ET_pred, 0)), #
            ET_ET_pred = mean(ifelse(ET>ET_pred, ET-ET_pred, 0)), #
            ag_ET = mean(ag_ET), #
            ET = mean(ET), #
            ET_pred = mean(ET_pred), #
            latitude = mean(latitude), #
            unused_rain = mean(ifelse(ETc<Pcp, Pcp-ETc, 0)),
            ETc = mean(ETc), 
            Pcp = mean(Pcp), 
            Er = mean(Er), 
            Spg = mean(Spg), 
            Espg = mean(Espg), 
            AW = mean(AW), 
            irr_eff = ag_ET_need/AW)
```



```{r}
ggplot(scatter_data) + 
  geom_abline(intercept=0,slope=1, color="red") + 
  geom_point(aes(x = ETc + unused_rain, y = ET, color = latitude)) + 
  scale_color_distiller(palette="RdYlBu", direction=1, name = "Latitude") + 
  geom_smooth(aes(x = ETc + unused_rain, y = ET), method="lm") + 
  theme_classic() + 
  ylab("Observed ET (mm/month)") + 
  xlab("CalSIMETAW ETc + Unused rain (mm/month)")

ggplot(scatter_data) + 
  geom_abline(intercept=0,slope=1, color="red") + 
  geom_point(aes(x = ET, y = ETc + unused_rain, color = latitude)) + 
  scale_color_distiller(palette="RdYlBu", direction=1, name = "Latitude") + 
  geom_smooth(aes(x = ET, y = ETc + unused_rain), method="lm") + 
  theme_classic() + 
  xlab("Observed ET (mm/month)") + 
  ylab("CalSIMETAW ETc + Unused rain (mm/month)")

scatter_data$total_CS_ET = scatter_data$ETc+scatter_data$unused_rain

lm(total_CS_ET~ET, scatter_data) %>% summary()
lm(ET~total_CS_ET, scatter_data) %>% summary()
```

```{r}
ggplot(scatter_data) + 
  geom_abline(intercept=0,slope=1, color="red") + 
  geom_point(aes(x = ag_ET, y = ag_ET_need, color = latitude)) + 
  scale_color_distiller(palette="RdYlBu", direction=1, name = "Latitude") + 
  geom_smooth(aes(x = ag_ET, y = ag_ET_need), method="lm") + 
  theme_classic() + 
  xlab("Empirical Agricultural ET (mm/month)") + 
  ylab("CalSIMETAW Agricultural ET (mm/month)")

ggplot(scatter_data) + 
  geom_abline(intercept=0,slope=1, color="red") + 
  geom_point(aes(x = ag_ET_need, y = ag_ET,  color = latitude)) + 
  scale_color_distiller(palette="RdYlBu", direction=1, name = "Latitude") + 
  geom_smooth(aes(x = ag_ET_need, y = ag_ET), method="lm") + 
  theme_classic() + 
  ylab("Empirical Agricultural ET (mm/month)") + 
  xlab("CalSIMETAW Agricultural ET (mm/month)")

lm(ag_ET_need~ag_ET, scatter_data) %>% summary()
lm(ag_ET~ag_ET_need, scatter_data) %>% summary()
```

# If you use ET_pred instead of ET
```{r}
ggplot(scatter_data) + 
  geom_abline(intercept=0,slope=1, color="red") + 
  geom_point(aes(x = ag_ET, y = ETc_ET_pred, color = latitude)) + 
  scale_color_distiller(palette="RdYlBu", direction=1, name = "Latitude") + 
  geom_smooth(aes(x = ag_ET, y = ETc_ET_pred), method="lm") + 
  theme_classic() + 
  xlab("Empirical Agricultural ET (mm/month)") + 
  ylab("CalSIMETAW Agricultural ET (mm/month)")

ggplot(scatter_data) + 
  geom_abline(intercept=0,slope=1, color="red") + 
  geom_point(aes(x = ETc_ET_pred, y = ag_ET,  color = latitude)) + 
  scale_color_distiller(palette="RdYlBu", direction=1, name = "Latitude") + 
  geom_smooth(aes(x = ETc_ET_pred, y = ag_ET), method="lm") + 
  theme_classic() + 
  ylab("Empirical Agricultural ET (mm/month)") + 
  xlab("CalSIMETAW Agricultural ET (mm/month)")

lm(ETc_ET_pred~ag_ET, scatter_data) %>% summary()
lm(ag_ET~ETc_ET_pred, scatter_data) %>% summary()
```

```{r}
cols <- c("#89C5DA", "#DA5724", "#74D944", "#CE50CA", "#3F4921", "#C0717C", "#CBD588", "#5F7FC7", 
"#673770", "#D3D93E", "#38333E", "#508578", "#D7C1B1", "#689030", "#AD6F3B", "#CD9BCD", 
"#D14285", "#6DDE88")
ggplot(scatter_data) + 
  geom_abline(intercept=0,slope=1, color="red") + 
  geom_point(aes(x = ETc_ET_pred, y = ag_ET,  color = cropnames)) + 
  scale_color_manual(values=cols) + 
  geom_smooth(aes(x = ETc_ET_pred, y = ag_ET), method="lm") + 
  theme_classic() + 
  ylab("Empirical Agricultural ET (mm/month)") + 
  xlab("CalSIMETAW Agricultural ET (mm/month)")
```


# If you calculate ag_ET on a monthly level and set to 0 if ET_pred>ET like you do for CalSIMETAW
```{r}
ggplot(scatter_data) + 
  geom_abline(intercept=0,slope=1, color="red") + 
  geom_point(aes(x = ET_ET_pred, y = ETc_ET_pred, color = latitude)) + 
  scale_color_distiller(palette="RdYlBu", direction=1, name = "Latitude") + 
  geom_smooth(aes(x = ET_ET_pred, y = ETc_ET_pred), method="lm") + 
  theme_classic() + 
  xlab("Empirical Agricultural ET (mm/month)") + 
  ylab("CalSIMETAW Agricultural ET (mm/month)")

ggplot(scatter_data) + 
  geom_abline(intercept=0,slope=1, color="red") + 
  geom_point(aes(x = ETc_ET_pred, y = ET_ET_pred,  color = latitude)) + 
  scale_color_distiller(palette="RdYlBu", direction=1, name = "Latitude") + 
  geom_smooth(aes(x = ETc_ET_pred, y = ET_ET_pred), method="lm") + 
  theme_classic() + 
  ylab("Empirical Agricultural ET (mm/month)") + 
  xlab("CalSIMETAW Agricultural ET (mm/month)")

lm(ETc_ET_pred~ET_ET_pred, scatter_data) %>% summary()
lm(ET_ET_pred~ETc_ET_pred, scatter_data) %>% summary()
```

# Precipitation vs natural ET
```{r}
ggplot(scatter_data) + 
  geom_abline(intercept=0,slope=1, color="red") + 
  geom_point(aes(x = ET_pred, y = Pcp, color = latitude)) + 
  scale_color_distiller(palette="RdYlBu", direction=1, name = "Latitude") + 
  geom_smooth(aes(x = ET_pred, y = Pcp), method="lm") + 
  theme_classic() + 
  xlab("Simulated natural ET (mm/month)") + 
  ylab("CalSIMETAW Pcp (mm/month)")

ggplot(scatter_data) + 
  geom_abline(intercept=0,slope=1, color="red") + 
  geom_point(aes(x = Pcp, y = ET_pred, color = latitude)) + 
  scale_color_distiller(palette="RdYlBu", direction=1, name = "Latitude") + 
  geom_smooth(aes(x = Pcp, y = ET_pred), method="lm") + 
  theme_classic() + 
  ylab("Simulated natural ET (mm/month)") + 
  xlab("CalSIMETAW Pcp (mm/month)")
```
